### ISSUE TITLE
codes about model

### ISSUE THREAD

**Issue by fanruiwen** [StonyBrookNLP/musique#1]
Hello！I am very glad to see this work.The dataset has highly quality and question decompose methods are very effective. I also study multi-hop reading comprehension and my postgraduate's projects is solve multi-hop reading comprehension via decompose multi-hop question. When I read your work's code.I can not find code about model.There are only have the evalution step code. Could you please release your work code about model ? Thanks a lot.

**Comment by HarshTrivedi** [comment]
Hi @fanruiwen! Thank you for your interest. I'd be releasing code to train/evaluate our models on the dataset. But unfortunately, it'd be a couple of months before I'll be able to get to it.

**Comment by fanruiwen** [comment]
OK，I will be especially looking forward to
